### ISSUE TITLE
Arrows conflict with floating video players

### ISSUE THREAD

**Issue by paul1149** [pratikabu/scrolltotop#165] opened 2023-07-27 21:13 UTC
Often now, sites will spawn a video player as soon as you start scrolling downward. They REALLY want you to spend time on their page.

I have the arrows on the right, mid-screen, and very often they conflict with the [X] close button on the video.

Would it be possible to have a hotkey that temporarily hides the arrows, so I can get to the video close button?

Great extension, BTW.

Thanks much,
Paul

**Comment by pratikabu** [comment] 2023-08-24 19:53
thanks Paul, glad that this extension is useful for you. Another user has requested a feature to have customizable shortcut keys #166. I'm going to club your request as well with that and see how much work will it be.

**Comment by pratikabu** [comment] 2024-01-08 04:15
Closing as duplicate of #166

**Closed by pratikabu** 2024-01-08 04:15 UTC
