### ISSUE TITLE
Odd behavior on different pages

### ISSUE THREAD

**Issue by nollinvoyd** [pratikabu/scrolltotop#172] opened 2024-02-11 18:10 UTC
I returned to this site today, and saw this

![scroll](https://github.com/pratikabu/scrolltotop/assets/20844322/59da3d89-0c7a-43ab-b660-a3e2f05e4cc1)

I had to restore the default settings to get rid of it, but I still get this on "some" other pages, but no other icons elsewhere on the page, including this site

![scroll5](https://github.com/pratikabu/scrolltotop/assets/20844322/21d9e156-554f-46d1-af99-c8ca1b1af310)

However, not on some other pages, like Youtube

**Comment by pratikabu** [comment] 2024-02-11 18:20
What browser are you using? And share the url of the sites on which it is not working. I'll check from my end.

**Comment by nollinvoyd** [comment] 2024-02-12 00:32
Firefox 122.01

[]https://www.americangreetings.com/cards/ecards/_/N-1x91zju(url)

The other instance is this webpage, Github  The image shows the arrow icon in the left upper corner that should not be there.

**Comment by nollinvoyd** [comment] 2024-02-12 00:53
Here's another with misplaced icons

![scroll8](https://github.com/pratikabu/scrolltotop/assets/20844322/4606b82b-d6f5-497b-8595-8e0362364d15)

[https://coupons.albertsons.com/weeklyad](url)

![alb](https://github.com/pratikabu/scrolltotop/assets/20844322/a7c7bc1a-77b2-43d7-9aa5-b9bd4670a059)

![alb2](https://github.com/pratikabu/scrolltotop/assets/20844322/a3818d7a-82af-4486-8304-86f7d2b2af0f)

**Comment by pratikabu** [comment] 2024-04-10 01:56
@nollinvoyd it looks like there is some other issue in your browser. I tested the extension on the URLs that you provided. I see a different behavior.

Have an issue on this site:
https://www.americangreetings.com/cards/ecards/_/N-1x91zju

I'll provide a fix to it. The issue is that on this site there is a global CSS config which set the image width to 100%.
<img width="399" alt="image" src="https://github.com/pratikabu/scrolltotop/assets/470973/be8354ec-0bd0-44c7-86cc-ca74f6021ceb">


Works good on these sites:
https://github.com/pratikabu/scrolltotop
https://coupons.albertsons.com/weeklyad

**Comment by pratikabu** [comment] 2024-04-10 05:47
I've published a new version 5.1 of Scroll To Top which has above fix. Kindly revalidate on Firefox.
https://addons.mozilla.org/en-US/firefox/addon/scroll-to-top/

Closing this ticket, kindly add your comment if you see any other issue.

**Closed by pratikabu** 2024-04-10 05:47 UTC
