### ISSUE TITLE
Issues on some sites

### ISSUE THREAD

**Issue by apopticon** [pratikabu/scrolltotop#87] opened 2020-03-06 15:01 UTC
One such site that has an issue is Instagram.com - As soon as you put mouse overscrolltotop icon, all of the elements become stacked, as show in the attached image.

![image](https://user-images.githubusercontent.com/60116359/76094815-3b6b3600-5f91-11ea-9f68-be611530fa1d.png)

**Comment by pratikabu** [comment] 2020-03-08 01:46
Yup i see that. Will try to figure out the root cause. thanks

**Comment by pratikabu** [comment] 2020-03-08 05:37
The issue has been identified and fixed. I'll release this soon. Thanks for notifiying.
It was happening because instagram uses display: flex by default. This addon expects the display to be set as block. I updated the code to do that and tested the same.

**Comment by apopticon** [comment] 2020-03-08 06:22
That's awesome - thanks! Is this possibly related to the horizontal / vertical offset settings in advanced? They don't seem to do much on most pages. Often winds up where the scrolltotop icon overlays a page's nav icon on the middle right side of a page, for example when there is right/left navigation arrows.

**Comment by pratikabu** [comment] 2020-03-09 02:11
No this has to do something with how `div` tag uses `display: flex` instead of `display: block`. Something related to CSS.

**Comment by pratikabu** [comment] 2020-05-18 01:35
This issue was fixed in https://github.com/pratikabu/scrolltotop/releases/tag/v4.8.1.
Closing this issue.

**Closed by pratikabu** 2020-05-18 01:35 UTC
